### ISSUE TITLE
Assembly scan failure should not crash the Bus

### ISSUE THREAD

**Issue by alprema** [Abc-Arbitrage/Zebus#36]
At startup, the Bus scans local assemblies for handlers, if an assembly cannot be loaded, the bus crashes. It should just ignore assemblies that cannot be scanned (with a warning).

**Comment by ablanchet** [comment]
In my opinion we should analyze all the assemblies found in the bin path with [Cecil](https://github.com/jbevain/cecil) in order to find the ones that contains at least one class that implement an IMessageHandler. And then load only those ones and ignore it if the load fails.

The first step is not mandatory but it allows us to load in the AppDomain only the _useful_ assemblies (and not all assemblies in the bin path). 
On the other hand ... it adds a new dependency to the bus.

**Comment by ablanchet** [comment]
I did some investigations :

**Question 1** : Should we use Cecil in order to avoid loading all assemblies in AppDomain for reflection purposes ?
 > Nope ! It's useless because we are running the reflection process on assemblies that are already loaded in the AppDomain. ([GetTargetAssemblies in TypeSource](https://github.com/Abc-Arbitrage/Zebus/blob/master/src/Abc.Zebus/Scan/TypeSource.cs#L29))

**Question 2** : Since we are processing assemblies that are already in the AppDomain, how could the scanning process throws exception ? 
> The assemblies are indeed correctly loaded, but the reflection on types could throw. For example if a type inherits of an unkown type (because its defining assembly is missing). In this case a [ReflectionTypeLoadException](https://msdn.microsoft.com/en-us/library/system.reflection.reflectiontypeloadexception(v=vs.110).aspx) is thrown when calling [GetTypes() here](https://github.com/Abc-Arbitrage/Zebus/blob/master/src/Abc.Zebus/Scan/TypeSource.cs#L22)

**Question 3**: Should we really want to ignore those exceptions ?
> I think not. It would risk to introduce sneaky bugs when silently ignoring assemblies that contains "broken" types. Those exceptions are only catched in the Bus.Start method and then re-throwns. Thus the bus will not be able to be started. I prefere a clean start or a total crash rather a half broken one.

**Next actions to do :**
1. Expose a more simple way _(or just a better documented way)_ to ignore assemblies from scanning. Ex : If you know you have assemblies that contains "broken" types that you know are not handlers, you may want to ignore those assemblies.
2. Cleanup the implementation of TypeSource in order to avoid the [legacy loading of Abc.* assemblies](https://github.com/Abc-Arbitrage/Zebus/blob/master/src/Abc.Zebus/Scan/TypeSource.cs#L27).
