### ISSUE TITLE
Switch to new SymbolSource repository

### ISSUE THREAD

**Issue by alprema** [Abc-Arbitrage/Zebus#44]
SymbolSource updated their engine (http://tripleemcoder.com/2015/10/04/moving-to-the-new-symbolsource-engine/). We should migrate to the new one since the old engine is quite slow at times.

**Comment by ablanchet** [comment]
What if instead of using symbol source we use 'gitlink' ? We can update our cake build file to use gitlink in order to link the generated pdbs to source code hosted on github.

Details about gitlink here : https://github.com/gittools/gitlink
How to use it in cake : http://cakebuild.net/api/cake.common.tools.gitlink/c4716228/eefcf7dd

**Comment by ltrzesniewski** [comment]
We now use [SourceLink](https://github.com/dotnet/sourcelink) in v3.
