### ISSUE TITLE
Persistence doesn't work

### ISSUE THREAD

**Issue by DiegoTondim** [Abc-Arbitrage/Zebus#66]
I implemented the BusConfiguration class, with IsPersistent = true, when I executed the application, after some seconds, the application break down.

What's the correct form of configuration to persistence works?

**Comment by MendelMonteiro** [comment]
Hi, 

Currently the only implementation that exists for the [Persistence service](https://github.com/Abc-Arbitrage/Zebus.Persistence) is available as a library and uses Cassandra as a store.

In order to get it running you would need to write a wrapper around it that hosts it and uses the implementations of the base interfaces which are present in the Persistence.CQL assembly.

We plan on providing a simple in-memory implementation (as we have done for the Directory service) and documenting the project better.

**Comment by MendelMonteiro** [comment]
You can see a sample of a runner project that uses the Cassandra implementation [here](https://github.com/Abc-Arbitrage/Zebus.Persistence/tree/master/src/Abc.Zebus.Persistence.Runner).

**Comment by DiegoTondim** [comment]
Hi,

ok... I'm using Directory Service, but If I send an event by node 1 and node 2 is down, the node 2 doens't receive it after starts.

**Comment by MendelMonteiro** [comment]
You need to run both the Directory service and the Persistence service.

**Comment by alprema** [comment]
I think you should be able to run it without the Persistence if you start a service with `IsPersistent = false` and your messages are marqued with the `[Transient]` attribute. See [this page](https://github.com/Abc-Arbitrage/Zebus/wiki/Persistence-Opt-out) for details

**Comment by ltrzesniewski** [comment]
I don't think he wants to opt out of the persistence 😉 

In order for a message to be persisted for a given service while it's down, the service needs to be registered on the directory. In your example, node 2 needs to have been started at least once in order to be registered. Then, when it goes down, the persistence will record the messages it should have received.

The following sequence of events should work:

 - Start the directory
 - Start the persistence
 - Start node 1
 - Start node 2
 - Stop node 2
 - Send your event
 - Node 1 should receive the event
 - Start node 2
 - Node 2 should receive the event

**Comment by ltrzesniewski** [comment]
Correct. We could provide a simple in-memory implementation suitable for a small development environment, just like the directory.

Note that an in-memory store is unsuitable for production usage:
- If the in-memory directory crashes or is stopped, you'll have to shutdown all of the services and start them again _after_ the directory has been restarted
- If the (currently non-existing) in-memory persistence crashes, you'll loose all messages targeted at stopped services.

We provide a Cassandra-backed implementation for both the directory and the persistence.
- This lets you start multiple directory services, eliminating the single point of failure which exists when you have a single directory instance. Upon restart, no data is lost.
- This lets you restart the persistence without losing any stored messages. Besides, this increases the persistence capacity.

Thus, our recommended approach is to always use the Cassandra-backed implementations, even for a development environment. Just deploy them on a development server and then forget they're there :)

**Comment by ltrzesniewski** [comment]
This is dealt with by #75, so I'm closing this issue to track the in-memory persistence progress there.
