### ISSUE TITLE
Cassandra Setup

### ISSUE THREAD

**Issue by veenroid** [Abc-Arbitrage/Zebus#79]
Love your implementation of ZeroMQ. I've been studying your code for a bit and can't find any details on utilizing Cassandra in place of your in-memory Directory.  Do you have anything you can point me to?  Is this lack of Cassandra detail what you meant in this quote from README?  If not, what do you mean?

> Although we did not release all the necessary bricks yet so you will have to wait a few minor versions to have a fully resilient prodable product.

Thanks for sharing your fantastic work.

**Comment by ltrzesniewski** [comment]
Thanks! 😄 

I'm not really sure why we didn't publish a ready-to-run Cassandra directory. Probably because you need to set-up a Cassandra cluster to run it first and most people wouldn't want to do this just to test the bus.

Internally, we're using a very thin wrapper around `Abc.Zebus.Directory.Cassandra`.

While the in-memory version declares `c.ForSingletonOf<IPeerRepository>().Use<MemoryPeerRepository>();` in StructureMap, the Cassandra version needs to use `CqlPeerRepository` instead of `MemoryPeerRepository`.

You'll also need to create the schema, which is provided [here](https://github.com/Abc-Arbitrage/Zebus/blob/master/src/Abc.Zebus.Directory.Cassandra/schema_creation.cql), and supply the necessary connection configuration by providing an implementation of [`ICassandraConfiguration`](https://github.com/Abc-Arbitrage/Zebus/blob/master/src/Abc.Zebus.Directory.Cassandra/Cql/ICassandraConfiguration.cs).

We have a work item (#78) which adds a runnable persistence in either RocksDB or Cassandra mode. We probably should provide a similar feature for the directory (to choose between in-memory and Cassandra).

/cc @ocoanet

**Comment by veenroid** [comment]
Thank you so much!

**Comment by MendelMonteiro** [comment]
@veenroid I've added a couple of lines to the Directory runner so that it is trivial to use it with Cassandra.

Check out this commit : https://github.com/Abc-Arbitrage/Zebus/commit/8633ecb829a3e51f9f22123c4b10f0e9cf0936cb
