### ISSUE TITLE
Large number of ports in use

### ISSUE THREAD

**Issue by dannylindquist** [Abc-Arbitrage/Zebus#81]
Hey team,

First of all, I want to say that this is a pretty cool project and it has been really easy to get up and running. I just got a test up and running and on about 40 computers at our office all connected to a single Directory Service. We opened up [TCPView](https://docs.microsoft.com/en-us/sysinternals/downloads/tcpview) to see what the network effect of every computer running a bus and at first glance it appears all the peers have a direct connection to every other peer? Is this the correct behavior? Could I get a little more detail on what each peer is connected to?

Just for reference. This is what the setup looks like.

Directory Service Initialization
```csharp
public void Start() {

    _busFactory = new BusFactory();
    InjectDirectoryServiceSpecificConfiguration(_busFactory);

    _busFactory
        .WithConfiguration(new AppSettingsBusConfiguration(), ConfigurationManager.AppSettings["Environment"])
        .WithScan()
        .WithEndpoint(ConfigurationManager.AppSettings["Endpoint"])
        .WithPeerId(ConfigurationManager.AppSettings["PeerId"]);

    _busFactory.CreateAndStartBus();
    _log.Info("In memory directory started");

    _log.Info("Starting dead peer detector");
    _deadPeerDetector = _busFactory.Container.GetInstance<IDeadPeerDetector>();
    _deadPeerDetector?.Start();

}

public void Stop() {
    _log.Info("Stopping dead peer detector");
    _deadPeerDetector?.Stop();
}

private void InjectDirectoryServiceSpecificConfiguration(BusFactory busFactory) {
    busFactory.ConfigureContainer(c => {
        c.AddRegistry<DirectoryRegistry>();
        c.ForSingletonOf<IDirectoryConfiguration>().Use<AppSettingsDirectoryConfiguration>();

        c.For<IDeadPeerDetector>().Use<DeadPeerDetector>();
        c.ForSingletonOf<IPeerRepository>().Use<MemoryPeerRepository>();
        c.ForSingletonOf<PeerDirectoryServer>().Use<PeerDirectoryServer>();
        c.ForSingletonOf<IPeerDirectory>().Use(ctx => ctx.GetInstance<PeerDirectoryServer>());

        c.ForSingletonOf<IMessageDispatcher>().Use(typeof(Func<IContext, MessageDispatcher>).Name, ctx => {
            var dispatcher = ctx.GetInstance<MessageDispatcher>();
            dispatcher.ConfigureHandlerFilter(x => x != typeof(PeerDirectoryClient));

            return dispatcher;
        });
    });
}
```

Then to connect to it, we use something like this:
```csharp
_container = new Container();
_container.Configure(x => x.ForSingletonOf<BridgeFourLegacy>().Use(this));
var factory = new Abc.Zebus.Core.BusFactory(_container);

factory
    .WithConfiguration("tcp://Bridge4:129", "Demo")
    .WithPeerId($"BridgeFourLegacy.*")
    .WithHandlers(typeof(LegacyMessageReceivedHandler));

_bus = factory.CreateAndStartBus();
```

Thanks so much.

**Comment by ocoanet** [comment]
Hello.

> at first glance it appears all the peers have a direct connection to every other peer?

In a standard setup, every peer:
- is connected to the directories and
- is connected to the recipient peers, i.e., the peers  that it needs to send message to.

I assume that in your setup, every peer has a handler for the same event, so when this event gets published, the sender must open a connection to every other peer.

**Comment by dannylindquist** [comment]
Thank you so much for clarifying. That makes sense. 👍

**Comment by ocoanet** [comment]
By the way, you should probably specify `.WithScan()` in your client configuration instead of `WithHandlers()`. Using `WithHandlers` you need to explicitly add every new handler in your factory.

**Comment by veenroid** [comment]
I was just curious about what this looked like.  From the sample solution I've run the standalone directory with just the publisher.listener and the publisher.sender demos. I've included a screenshot showing 47 ports in total. This is all running on a single machine. Is that expected?  I'm curious how many peers you typically run on your bus? Can you speak to scalability and ephemeral port exhaustion? We are dreaming of building several distributed and highly interconnected services using zebus as the backbone. The services would connect to a large number of endpoints. Am I thinking about this the wrong way? 

![abc zebus ports](https://user-images.githubusercontent.com/6529698/54549623-afb75e80-4967-11e9-81a7-9561e836eee4.png)

**Comment by ocoanet** [comment]
Because Zebus is peer-to-peer based, it tends to create many TCP connections, especially if you need to send "broadcast" messages, that is, messages that will received by many other peers. However, we are running two Zebus environments, one with around 300 peers and one with around 750 peers and we have no port exhaustion issues.

I will have a look at the sample solution the week to make sure that the configuration is correct and does not generate extra connections.

**Comment by veenroid** [comment]
750!  Awesome. Thank you for your efforts.

**Comment by ocoanet** [comment]
Ok, I just checked the socket usage. It is clearly quite high! However, you might notice that most of the sockets are local-only: they are internal ZMQ sockets.

## Internal ZMQ sockets

Zebus uses ZMQ sockets to send and receive messages. Those sockets are high level components that can create multiple TCP sockets to communicate with multiple nodes. But ZMQ does not only create sockets for inter-node messaging: it also uses TCP sockets for its internal inter-thread communications.

Starting a ZMQ context (with no ZMQ sockets) creates 2 "local" TCP sockets on my machine:
```
using (var context = new ZmqContext())
{
    Console.WriteLine("Context created");
    Console.WriteLine("Press enter to exit...");
    Console.ReadLine();
}
```
Creating and binding a ZMQ PULL socket adds 6 "local" TCP sockets and 1 "network" TCP socket:
```
using (var socket = new ZmqSocket(context, ZmqSocketType.PULL))
{
    socket.Bind("tcp://*:123");

    Console.WriteLine("Socket bound");
    Console.WriteLine("Press enter to exit...");
    Console.ReadLine();
}
```
If port usage is not an issue on your environment, you can ignore the "local" sockets. If this is an issue for you, there is not much we can do because those sockets are a ZMQ implementation detail.

## ZMQ inter-node sockets

Zebus uses [PULL](http://api.zeromq.org/4-2:zmq-socket#toc16) and [PUSH](http://api.zeromq.org/4-2:zmq-socket#toc15) ZMQ sockets. Every Zebus peer has one PULL socket for inbound messages and multiple PUSH sockets for outbound messages, one for each target peer.

The PULL/PUSH ZMQ sockets should generate one inter-node TCP socket every time a peer needs to send messages to an other peer. However, because those sockets are unidirectional, another pair of PULL/PUSH ZMQ sockets is used for communication in the other direction, which creates another inter-node TCP socket.

So, the inter-node TCP socket usage is slightly sub-optimal: 2 sockets are created for bidirectional communication when just one could be used. This behavior is not an issue for us despite the large number of peers that we run in our production environment. If you think it is an issue for you, it might be possible to add an option to use different, bidirectional, ZMQ socket types.


Hope this helps.
