### ISSUE TITLE
Make startup subscription configurable

### ISSUE THREAD

**Issue by ltrzesniewski** [Abc-Arbitrage/Zebus#99]
Add something to make `MessageShouldBeSubscribedOnStartup` configurable more dynamically (with a callback).

The goal would be to be able to define a subscription filter on service startup more easily.

**Comment by ltrzesniewski** [comment]
Also, currently there is no way to configure multiple filters in `MessageDispatcher`, and if I want to force a specific `IMessageHandlerInvoker` to be loaded, it still needs to satisfy the user's filters. When using `BusFactory`, I cannot add a filter from a registry.

**Comment by ocoanet** [comment]
Also, there is no way to subscribe before `Bus.Start`. It would be nice to support `Bus.Subscribe` before start, and simply send the subscriptions on start during the registration. But I guess that's a bit off topic :)

**Comment by ltrzesniewski** [comment]
@ocoanet I started implementing something, so let's talk philosophy

```C#
var fooTask = bus.SubscribeAsync(foo);

// fooTask should not be completed before the bus starts, right? 🤔

// Should we make sure that we have a handler for foo, when not using ThereIsNoHandlerButIKnowWhatIAmDoing? 🤔
// That would force us to load the handlers before the bus starts, which would be unexpected.

bus.Start();

bus.Subscribe(bar);

bus.Stop();
bus.Start();

// Should foo be subscribed on the second start? 🤔
// It may be needed by a component which expects this message to be subscribed independently of bus start/stop.

// Is foo really that different from bar? 🤔

```

**Comment by ocoanet** [comment]
> // fooTask should not be completed before the bus starts, right? 🤔

No, we can assume that the subscription will be sent with other startup subscriptions on start. It could be acceptable to return a completed task here because the subscription is already registered (locally) and it cannot fail (unless `IBus.Start` fails).

Also, there is no code that invokes `Subscribe` before `Start` right now because it is not supported. We can decide what we believe is more appropriate for this scenario without breaking anything.

> // Should we make sure that we have a handler for foo, when not using ThereIsNoHandlerButIKnowWhatIAmDoing? 🤔
> // That would force us to load the handlers before the bus starts, which would be unexpected.

Ok, to be honest I knew we would have to solve this. I think that dynamically triggering invoker loading is a valid option. It seems a little dangerous but there is a fixed set of invoker loaders and invokers, so we could review them to make sure that creating them before `Start` does not have side effects. Another option here is to skip the invoker check for startup subscriptions.

> // Should foo be subscribed on the second start? 🤔

I would say yes, the subscription is still active in the "startup" subscriptions of the bus, unless you dispose the subscription.

I notice that all your questions come from the fact that the startup subscriptions use the same API as standard subscriptions with a slightly different behavior. Maybe using a different API like `IBus.AddStartupSubscription` would make the behavior change more explicit.

Altogether it seems that this feature is quite complex. Yet, I still think it would be useful and easy to use. For comparison, we could decide to support `IMessageDispatcher.AddInvoker` before bus start instead: it would be much easier to implement but it would not be as useful.

If your initial goal is simply to improve the IMessageHandlerInvoker API, maybe we could go back to this and take some time to think about startup subscriptions.

**Comment by ltrzesniewski** [comment]
> It could be acceptable to return a completed task here because the subscription is already registered (locally) and it cannot fail

That's true, and there are some advantages as well: it makes the sync `Subscribe` work, and you can dispose of the subscription before the bus starts.

> Another option here is to skip the invoker check for startup subscriptions.

I think that's better. Let's suppose you know what you're doing if you subscribe before start.

> Maybe using a different API like `IBus.AddStartupSubscription` would make the behavior change more explicit.

I'd prefer to avoid a breaking change for such a minor feature.

> Altogether it seems that this feature is quite complex.

Quite honestly, I implemented it easily but it still needs a few changes (like the behavior after a restart), and I'm not quite satisfied with it yet.

> If your initial goal is simply to improve the IMessageHandlerInvoker API

I think several goals piled up here 😉 

> // Is foo really that different from bar? 🤔

The underlying question was really: should we really dispose the subscription to bar when stopping the bus? Unfortunately, that would be a rather big breaking change.

**Comment by ocoanet** [comment]
`ShouldBeSubscribedOnStartup` was replaced by `GetStartupSubscriptions()`, which is implemented using the new `IStartupSubscriber` interface (in [this change](https://github.com/Abc-Arbitrage/Zebus/commit/bae0344499739493ad59f10c00479844ee17e917)).

Is this issue still valid now?

**Comment by ltrzesniewski** [comment]
Nice! 👍
